### ISSUE TITLE
1.0.0-beta.6 compatibility with latest stable Ktor

### ISSUE THREAD

**Issue by harry248** [Kamel-Media/Kamel#107]
I tried the 1.0.0-beta.6 (mainly because I need to set `maxBitmapDecodeSize`) but I am getting a `Could not find io.ktor:ktor-client-core:3.0.0-beta-2-eap-939.` compile error.

The project is using a stable Ktor version (2.3.12 right now). Does it really make sense for Kamel to use EAP versions of its own dependencies?

**Comment by luca992** [comment]
Sorry. It's just too much work for me to maintain a separate build with and without wasm at least on the beta. If you want to make a fork with wasm removed and on stable ktor, just make a pr and I can publish it for you. I'm keeping the pre 1.0.0 releases on stable ktor. I also didn't expect 3.0.0 beta 2 to take this long to be released. They were saying two months ago it would be out soon. 1.0.0 is basically being held up by ktor

**Comment by luca992** [comment]
@harry248 looks like next week the next ktor release should be published. https://kotlinlang.slack.com/archives/C0A974TJ9/p1719388699260549

I'll update it as soon as it's out. But it's not worth the effort if it's coming out next week imo

**Comment by luca992** [comment]
@harry248 https://github.com/Kamel-Media/Kamel/releases/tag/v1.0.0-beta.7 has 3.0.0 beta 2 from maven central now
