### ISSUE TITLE
Duplicate class co.touchlab.stately.collections.FunctionsKt

### ISSUE THREAD

**Issue by latrus94** [Kamel-Media/Kamel#109]
Hi,

I want to update KamelMedia library into the latest version, but I receive this error on build:

`Duplicate class co.touchlab.stately.collections.FunctionsKt found in modules stately-collections-jvm-2.0.7 (co.touchlab:stately-collections-jvm:2.0.7) and stately-iso-collections-jvm-2.0.5 (co.touchlab:stately-iso-collections-jvm:2.0.5)`

I'm using kotlin multiplatform project and I'm using stately library also in other module but.

I tried to exclude this library I'm using in differenet module:

```
implementation("media.kamel:kamel-image:0.9.2") {
   exclude(
      group = "co.touchlab",
      module = "stately-collections-jvm" <-- this library I'm using in the different module
   )
}
```

Do you know how can I fix it?

**Comment by latrus94** [comment]
I fixed this problem. Exclude should be declared in every module that inherits from a module with KamelMedia dependency.

maybe someone will find this solution useful someday :)

**Comment by luca992** [comment]
You're also not using the latest version of kamel `0.9.5` doesn't include stately anymore

**Comment by latrus94** [comment]
@luca992 I saw that 0.9.5 requires Kotlin 2.0.0, I'm not ready for that update yet

**Comment by latrus94** [comment]
@luca992 are you sure Kamel in version 0.9.5 do not include stately?

**Comment by luca992** [comment]
Actually I guess we are transitively including stately 2.0.6 through [cache4k](https://github.com/ReactiveCircus/cache4k/releases)
