### ISSUE TITLE
Image does not load in iOS with custom Kamel Config

### ISSUE THREAD

**Issue by erickvelasco11** [Kamel-Media/Kamel#118]
Hi 
Thanks for your work here and given us this library. It's really useful because load images by URL should be a basic functionality of Kotlin. however, you've made a great job.
I have an issue. When I use Kamel to load a profile image all works fine, but if I need to give the user the ability of change his photo, the photo does not update, because the cache maintain the old photo. I read the documentation and see I can invalidate the cache using a `Custom Kamel Config`, but when I use it in iOS, the image does not load.

This code works perfectly
```
KamelImage(
  {
      asyncPainterResource(data = urlImage)
  },
  contentDescription = "image",
  contentScale = ContentScale.Crop,
  modifier = modifier
      .size(radius)
      .clip(CircleShape)
      .clickable {
          onClick()
      },
  animationSpec = tween(),
  onFailure = {
      println("Error loading photo: ${it.message}")
      Image(
          painterResource(Res.drawable.default_profile),
          contentDescription = "Profile",
          modifier = Modifier
              .size(radius)
              .clip(CircleShape)
              .clickable { onClick() },
      )
  },
  onLoading = {
      Box(
          modifier = modifier
              .size(radius)
              .clip(CircleShape),
          contentAlignment = Alignment.Center
      ) {
          CircularProgressIndicator(color = loaderColor)
      }
  }
)
```

But this code does not work in iOS (Android works perfectly)
```
val customKamelConfig = KamelConfig {
    takeFrom(KamelConfig.Default)
    if (invalidateCache) {
        imageBitmapCacheSize = 1
    }
}

CompositionLocalProvider(LocalKamelConfig provides customKamelConfig) {
    /// Same code above
}
```

I really appreciate your help because if I don't invalidate the cache, the user changes his photo, but the image does not update.

Thanks

**Comment by erickvelasco11** [comment]
I think you aren't using the Native Ktor client to fetch the image when the cache is invalidated, because the issue in OnFailure is 

`Error loading photo: TLS sessions are not supported on Native platform.`

I'm using last version of Ktor in both platform, OKHTTP for Android and DARWIN for iOS, but the implementation for Kamel is internal.

**Comment by luca992** [comment]
Say you have `url_a` and `url_b`. If you have `imageBitmapCacheSize = 1` and load `url_a`, it will be cached in memory since you allowed one image to be cached. Now even if you change the image on the backend, `url_a` should get loaded from memory every time with the old image. However if you load `url_b` then `url_a` once again, it should be loading the new version of `url_a` since loading `url_b` wiped if from the cache if one one cached value is allowed.

Also if you are using the disk cache:

```
KamelConfig {
    httpFetcher {
        // The size of the cache can be defined in bytes. Or DefaultHttpCacheSize (10 MiB) can be used. 
        httpCache(DefaultHttpCacheSize)
    }
}
```

even if you wipe the memory cache, ktor will try to get it from the disk cache before attempting to make a network call. So you may need disable/ delete the disk cache. 

...Off hand I'm not sure if we added a way to invalidate a specific cached entry yet 🤔

**Comment by luca992** [comment]
as for `Error loading photo: TLS sessions are not supported on Native platform.` if you can provide url that causes that I can take a look

**Comment by erickvelasco11** [comment]
I think this can be closed because is not an issue of the library, it's a different way to implement the HttpClient. I have fixed this using a different implementation in Android and in iOS

This is my KamelConfig

```
    val customKamelConfig = KamelConfig {
        takeFrom(KamelConfig.Default)
        if (invalidateCache) {
            imageBitmapCacheSize = 1
        }
        httpUrlFetcher(createHttpClient())
    }
```

`createHttpClient` is a expect function

`expect fun createHttpClient(): HttpClient`

And the implementation for each platform is like this

Android
```
actual fun createHttpClient(): HttpClient {
    return HttpClient(OkHttp) {
        install(ContentNegotiation) {
            json(json = Json {
                /// JSON Options
        }
        install(HttpTimeout) {
            /// Timeout options
        }
    }
}
```

iOS
```
actual fun createHttpClient(): HttpClient {
    return HttpClient(Darwin) {
        install(ContentNegotiation) {
            json(json = Json {
                /// JSON Options
        }
        install(HttpTimeout) {
            /// Timeout options
        }
    }
}
```
