### ISSUE TITLE
Image is not loading

### ISSUE THREAD

**Issue by JagadishaIncture** [Kamel-Media/Kamel#129]
CMP : 1.7.1
Kotlin : 2.1.0
Kamel : 1.0.1

Geting Blank View
<img width="305" alt="Screenshot 2024-12-27 at 12 43 57 PM" src="https://github.com/user-attachments/assets/fb6e9a85-d082-402e-9056-1a29b7360520" />

sample url : https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg

`if (signatureUrl.isNotEmpty()) {

                    val getPainterResource: @Composable (BoxWithConstraintsScope.() -> Resource<Painter>) = {
                        asyncPainterResource(signatureUrl,
                            filterQuality = FilterQuality.High,
                        )
                    }
                    KamelImage(
                        resource = getPainterResource,
                        contentDescription = null,
                        modifier = Modifier.size(150.dp)
                    )
                } else {
                    Text(
                        text = "No Signature Available",
                        modifier = Modifier.fillMaxWidth(),
                        color = Color.Gray
                    )
                }`

**Comment by luca992** [comment]
Works fine. Debug errors with `onFailure`
```
KamelImage(
                { asyncPainterResource("https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg") },
                contentDescription = null,
                modifier = Modifier.size(150.dp),
                onFailure = { throw it }
            )
```
<img width="314" alt="Screenshot 2024-12-27 at 6 40 08 PM" src="https://github.com/user-attachments/assets/bf956986-41f8-47fa-ad6d-6fa47d5bdc97" />

**Comment by JagadishaIncture** [comment]
@luca992  tell me CMP version and kotlin version ?
