### ISSUE TITLE
Add js support

### ISSUE THREAD

**Issue by dragossusi** [Kamel-Media/Kamel#15]
Hello

Compose-jb is adding support for web foundation and material libraries.

I want to share all of my code across platforms (jvm ,android, web) and this library doesn't support js yet.

I think it's a good point to start implementing it until release of the stable compose release.

`1.2.0-alpha01-dev620` adds support for js, should be enough to start implementing a solution for js.

**Comment by luca992** [comment]
https://github.com/alialbaali/Kamel/pull/23

added support for js in my pr. You can test it out if you want.
The pr isn't complete yet, but remote and local images should work

**Comment by luca992** [comment]
v0.5.0 is out with js support
