### ISSUE TITLE
Could not HEAD 'https://dl.bintray.com/kotlin/dokka/io/codearte/nexus-staging/io.codearte.nexus-staging.gradle.plugin/0.22.0/io.codearte.nexus-staging.gradle.plugin-0.22.0.pom'. Received status code 502 from server: Bad Gateway

### ISSUE THREAD

**Issue by jerryion** [Kamel-Media/Kamel#22]
https://dl.bintray.com/kotlin/dokka/io/codearte/nexus-staging/io.codearte.nexus-staging.gradle.plugin/0.22.0/io.codearte.nexus-staging.gradle.plugin-0.22.0.pom

502 Bad Gateway

**Comment by alialbaali** [comment]
Do you have jcenter repository added in your Gradle repositories block?
