### ISSUE TITLE
Add persistent cache

### ISSUE THREAD

**Issue by denchic45** [Kamel-Media/Kamel#27]
Perhaps it would be worth adding image caching to the device memory so that you can always access them without a network?

**Comment by luca992** [comment]
I plan to implement this eventually. If you have any thoughts on how it should be implemented feel free to make suggestions.

**Comment by denchic45** [comment]
I think you need something like in coil or glide, but you also need to make it multiplatform

**Comment by luca992** [comment]
Released in `0.8.0`
