### ISSUE TITLE
Update compose-jb and kotlin version

### ISSUE THREAD

**Issue by 070hm** [Kamel-Media/Kamel#29]
Hi all, Thanks for this library, which is helpful, if you can update je-compose 1.3.0-beta04-dev873 to and Kotlin to 1.7.20 ,
because there is a crash when attempting to load a PNG image
`  val painterResource: Resource<Painter> = lazyPainterResource("https://cdn-bjkcl.nitrocdn.com/ZfEHGrbhkMgKTiTsiXTlOoOZBeNqAgPw/assets/static/optimized/rev-e4ff0d1/wp-content/uploads/2018/10/practice.png")`
**Error**
`java.lang.IllegalArgumentException: Failed to Image::makeFromEncoded`

See this for more details https://github.com/JetBrains/compose-jb/issues/124

Note :- I think if we update the compose will solve the problem , I'm not pretty sure +_+.

**Comment by xxfast** [comment]
Can we bump to the latest stable instead? 1.3.0 has gone stable

**Comment by luca992** [comment]
v0.5.0 is out with kotlin 1.8.20 and compose 1.40
