### ISSUE TITLE
lazyPainterResource and KamelImage not found

### ISSUE THREAD

**Issue by BILLyTheLiTTle** [Kamel-Media/Kamel#30]
I have a separate module for sharing the ui between android application and desktop application.
Although, I add the dependency in gradle [this way](https://github.com/BILLyTheLiTTle/Learning_Android/blob/main/MultiPlatformApplication/shared-ui/build.gradle.kts#L75) in the application code it cannot find the [lazyPainterResource where I want to use it](https://github.com/BILLyTheLiTTle/Learning_Android/blob/main/MultiPlatformApplication/shared-ui/build.gradle.kts#L75) and also [the KamelImage cannot be found](https://github.com/BILLyTheLiTTle/Learning_Android/blob/main/MultiPlatformApplication/shared-ui/src/commonMain/kotlin/learning/android/kmm/android/ui/MainContent.kt#L66) as well.
Am I doing something wrong? Would you like to have some more details?

**Comment by alialbaali** [comment]
I'm sorry, there's some issue going on with publishing Kotlin Multiplatform project after updating to Kotlin 1.7.0. I'm not sure what the issue is, I tried multiple solutions, and nothing has worked for me. If anyone has any idea how to fix it, it would be appreciated!

**Comment by fdale15** [comment]
![image](https://user-images.githubusercontent.com/14189398/211167482-782fef75-d816-4632-8be3-83e373a544fb.png)

It seems my project doesn't provide autocompletion and acts like it will not compile, but this does compile for me.
