### ISSUE TITLE
Refactor to use refreshVersions instead of organizing dependencies w/ buildSrc

### ISSUE THREAD

**Issue by luca992** [Kamel-Media/Kamel#34]
@alialbaali 
I'm a big fan of using https://github.com/Splitties/refreshVersions with a gradle versions catalog to organize dependencies. Would you allow a pr switching the repo use that setup?

**Comment by alialbaali** [comment]
Definitely! I use it myself in my other projects. 

I'm not sure if you noticed, but I also added you as collaborator. Feel free to use the repository however you want by creating releases, approving PRs, etc... As I don't have time to work on this project anymore :(

Thank you for all the work you've been doing!

**Comment by luca992** [comment]
#41
