### ISSUE TITLE
cannot inline bytecode built with JVM target 11

### ISSUE THREAD

**Issue by youranshul** [Kamel-Media/Kamel#38]
Hi , 
I am using this library on my Compose ios multiplatform app. Everything works fine on the ios app but when I compile and run Android app it throws this error.
`Cannot inline bytecode built with JVM target 11 into bytecode that is being built with JVM target 1.8. Please specify proper '-jvm-target' option`

And the error it throws on this line when I try to make asyncPainterResource: 
`val painterResource = asyncPainterResource(data = "https://image.tmdb.org/t/p/original${item.imageUrl}")`

I have my common build.gradle file here : https://pastebin.com/WcbmF812 

**version Used** : media.kamel:kamel-image:0.5.1

**Comment by youranshul** [comment]
@jakepurple13  thanks for the workaround. 
@contributers : do we have a proper fix for that?

**Comment by luca992** [comment]
You could just set your project's target to be JVM 11, or do you have a reason to not do that?

**Comment by youranshul** [comment]
@luca992 I created this kmm project through the android studio and did not set any jvm target manually. Why should i change that?

**Comment by luca992** [comment]
@youranshul android studio uses 11 by default. Try setting target and source compatibility to 11 like in the sample here: https://github.com/Kamel-Media/Kamel/blob/e3b58c0768c3993c13489a7f9cfceb640aa2e3a2/kamel-samples/build.gradle.kts#L28

**Comment by youranshul** [comment]
@luca992 I have tried setting it on Android's build.gradle.kts but the issue is the same.

**Comment by luca992** [comment]
I'm going to close this. If you want make a sample and I'll take another look. But here's some relevant info.

https://stackoverflow.com/questions/48988778/cannot-inline-bytecode-built-with-jvm-target-1-8-into-bytecode-that-is-being-bui

https://youtrack.jetbrains.com/issue/KTIJ-20816/Bogus-error-Cannot-inline-bytecode-built-with-JVM-target-11-into-bytecode-that-is-being-built-with-JVM-target-1.8.

**Comment by luca992** [comment]
try `0.7.2-SNAPSHOT` I think it should not have that issue anymore. I'll publish a new version if that works
