### ISSUE TITLE
Proguard removing necessary fetcher classes

### ISSUE THREAD

**Issue by rushiiMachine** [Kamel-Media/Kamel#47]
I'm forced to add this to my proguard rules otherwise Kamel refuses to load due to not being able to find classes through reflection

```pro
-keep class io.kamel.** { *; }
```

Is there a more accurate ruleset I can use rather than marking the whole lib to keep?

**Comment by luca992** [comment]
I finally just tried out using enabling minify and you're right. I'm just going t remove reflection in the next release and use the same method as every other non-jvm target.

**Comment by luca992** [comment]
fixed by a3720b8566c73de1589d7cd66306f127294f8c25
