### ISSUE TITLE
Kotlin 1.9.0

### ISSUE THREAD

**Issue by mahramane** [Kamel-Media/Kamel#49]
Kotlin 1.9.0 came.
Please use Kotlin 1.9.0.

**Comment by luca992** [comment]
There's no compose multiplatform build supporting 1.9.0 yet.

**Comment by luca992** [comment]
try `media.kamel:kamel-image:0.7.1-SNAPSHOT` . Just note, I'm having issues with the js sample, not sure if js is working.

**Comment by mahramane** [comment]
I'll update it.
Thank you very much.
