### ISSUE TITLE
D/skia: --- Failed to create image decoder with message 'unimplemented'

### ISSUE THREAD

**Issue by OysterD3** [Kamel-Media/Kamel#5]
I got this error when trying to load SVG/Vector Asset in android

```
D/skia: --- Failed to create image decoder with message 'unimplemented'
```

**Comment by alialbaali** [comment]
Vector/SVG assets loading isn't supported on Android. However you could implement a custom decoder and add it to `KamelConfig`.

**Comment by luca992** [comment]
svgs have been support on android since [v0.6.0](https://github.com/Kamel-Media/Kamel/releases/tag/v0.6.0)
