### ISSUE TITLE
Classes not found when running on iOS

### ISSUE THREAD

**Issue by Kashifmasood07** [Kamel-Media/Kamel#56]
I have added the dependency to common source set since I am using it for a multiplatform project and it works fine when I run Android app, but when I run it on iOS, I get following error.

`Could not find "/Users/mac/.gradle/caches/modules-2/files-2.1/media.kamel/kamel-image-iosarm64/0.7.2/33fd052e978bb1ea02569817afbfd6929a1e350a/kamel-image.klib" in [/Users/mac/Documents/Markaz-Supplier/markazSupplierIos/Pods, /Users/mac/.konan/klib, /Users/mac/.konan/kotlin-native-prebuilt-macos-x86_64-1.8.20/klib/common, /Users/mac/.konan/kotlin-native-prebuilt-macos-x86_64-1.8.20/klib/platform/ios_arm64]`

**Comment by luca992** [comment]
Can you try kotlin 1.9.0?

**Comment by luca992** [comment]
I added an ios sample and everything works. Provide an example if you want me to take a look.

**Comment by Kashifmasood07** [comment]
I couldn't migrate kotlin to 1.9 but I used kamel version 0.7.1 and it worked. Thanks.
The only problem I have right now is that ios app runs in to OOM error when loading a little large number of images. 
The images I load have the size range from 400kb-1mb. And there can be  a lots of images. So it runs in to OOM.

**Comment by luca992** [comment]
> > You probably need to update to compose 1.10.0 which[ 1.0.9 ](https://github.com/Kamel-Media/Kamel/releases/tag/v1.0.9)uses
> 
> Had already updated to compose `1.10.0` recently, but haven't updated to kotlin 2.3.0 yet, maybe something about that...

If it doesn't work after updating both please create an issue
