### ISSUE TITLE
use: io.ktor:ktor-client-darwin-legacy instead of io.ktor:ktor-client-darwin

### ISSUE THREAD

**Issue by liao123abc** [Kamel-Media/Kamel#57]
https://youtrack.jetbrains.com/issue/KTOR-4159

**Comment by luca992** [comment]
Is this an ios issue? The macOS sample works fine

**Comment by luca992** [comment]
I added an iOS sample, and everything is working. Also, I don't see why I should use darwin-legacy given the issue you linked is fixed.

**Comment by liao123abc** [comment]
@luca992  use a iOS 11 devices
