### ISSUE TITLE
Is there a method to encode data in Base64 and display it as an image?

### ISSUE THREAD

**Issue by wangzhigang1112** [Kamel-Media/Kamel#59]
"Data encoded in Base64 can be displayed on the web using an img tag. Can KamelImage support this?"

**Comment by luca992** [comment]
There isn't out of the box, I'm not sure how much demand there would be for that feature. But you could you could make your fetcher to convert the base64 to bytes. You may also want to create an accompanying  mapper as well for your source data type.
