### ISSUE TITLE
is it possible to apply blur effect on loaded image for Compose Desktop?

### ISSUE THREAD

**Issue by akardas16** [Kamel-Media/Kamel#60]

**Comment by luca992** [comment]
I don't see why not. Do it the same was as you would for a normal image in compose.

For example: https://devjorgecastro.medium.com/add-blur-effect-to-image-in-compose-b6c5b03864d

**Comment by akardas16** [comment]
```
KamelImage(resource = asyncPainterResource(data = text), contentDescription = "",
                onLoading = { CircularProgressIndicator(it) }, animationSpec = tween(), contentScale = ContentScale.Crop,
                modifier = Modifier.size(250.dp).clip(RoundedCornerShape(16.dp).blur(16.dp))
            )
```
above code is not working error says blur Modifier defined in androidx.compose.ui.draw

**Comment by akardas16** [comment]
> I don't see why not. Do it the same was as you would for a normal image in compose.
> 
> For example: https://devjorgecastro.medium.com/add-blur-effect-to-image-in-compose-b6c5b03864d

thank you
