### ISSUE TITLE
 Null pointer exception occurs on iOS

### ISSUE THREAD

**Issue by DJ-LEE11** [Kamel-Media/Kamel#66]
**Affected platforms**
- iOS

**Versions**
- Kamel version*: 0.7.0

**Crash Info**
![7CBCA0D1DA9016C4587CDD705](https://github.com/Kamel-Media/Kamel/assets/30454011/44f8af67-5645-40cd-a0ec-f59cf47185d9)

**Occurrence location**
<img width="772" alt="infoflow 2023-11-01 16-32-55" src="https://github.com/Kamel-Media/Kamel/assets/30454011/9cfbade5-996f-4673-8104-887f658be34f">

LinkedHashMap is thread-unsafe.

**Comment by luca992** [comment]
Yeah, that's defintely an issue with the LRU Cache. How often does it happen? Do you have a way to reproduce it regularly?

It's not thread safe:
see:
https://github.com/apollographql/apollo-kotlin/pull/2878
https://github.com/apollographql/apollo-kotlin/issues/2844

looks like using https://github.com/ReactiveCircus/cache4k could be a solution?

**Comment by DJ-LEE11** [comment]
This crash happened by chance.
Our current solution is to use Ktor provide thread-safe ConcurrentMap to replace LinkedHashMap.

<img width="857" alt="infoflow 2023-11-01 16-10-59" src="https://github.com/Kamel-Media/Kamel/assets/30454011/1aabbfb2-b5b0-461e-9c76-00d40110c61e">

**Comment by luca992** [comment]
<img width="878" alt="Screenshot 2023-11-02 at 3 32 32 AM" src="https://github.com/Kamel-Media/Kamel/assets/4157455/fe05df41-6cb0-4bc4-9a77-bb805a1657aa">

Making sure we use the same `coroutineContext` when loading a cached resource might be the issue. Idk have to look into it more.

**Comment by luca992** [comment]
but then again I don't think using a suspend there would be ideal 🤔

**Comment by luca992** [comment]
https://github.com/touchlab/Stately is another option

**Comment by luca992** [comment]
try `0.8.4` lmk if you have any problems. I switch it to being backed by stately's `ConcurrentMutableMap`
