### ISSUE TITLE
Add wasmJS target

### ISSUE THREAD

**Issue by luca992** [Kamel-Media/Kamel#85]
### Blocked by:
* https://youtrack.jetbrains.com/issue/KT-64638/java.util.NoSuchElementException-Key-CLASS-CLASS-nameURL-modalityOPEN-visibilitypublic-external-superTypeskotlin.js.JsAny-is
    * Needed for `URLMapper`
    
### Issues
* A stable build of cache4k with: https://github.com/ReactiveCircus/cache4k/pull/45 (`0.13.0-SNAPSHOT`is published and working)
*  ̶I̶n̶v̶e̶s̶t̶i̶g̶a̶t̶e̶ ̶w̶h̶y̶ ̶t̶h̶e̶ ̶I̶m̶a̶g̶e̶V̶e̶c̶t̶o̶r̶D̶e̶c̶o̶d̶e̶r̶ ̶(̶X̶M̶L̶)̶ ̶i̶s̶ ̶b̶r̶o̶k̶e̶n̶ ̶i̶n̶ ̶t̶h̶e̶ ̶s̶a̶m̶p̶l̶e̶

**Comment by armond1978** [comment]
@luca992 Is there any plan to add WASM support to 1.0.0-beta.* versions ? I can see "0.9.3-wasm" but nothing for the latest beta version.

**Comment by luca992** [comment]
@armond1978 Yeah soon enough. There's a few merge conflicts i need to handle that I haven't had time to get to yet.

**Comment by armond1978** [comment]
@luca992 I just noticed that `1.0.0-beta.3` depends on a dev version of Compose. Is it possible to utilize the latest stable version instead?

**Comment by armond1978** [comment]
@luca992 I see where the issue is. You can keep it as is if it resolves that bug.

**Comment by luca992** [comment]
publishing `1.0.0-beta.4` with kotlin `1.9.23` and compose `1.6.1` that has the fix @armond1978
