### ISSUE TITLE
how to skip memory cache in kamel

### ISSUE THREAD

**Issue by adelsaramii** [Kamel-Media/Kamel#87]
i want to load my image every time cuz the image file on server would change and url stand the same
so i need to load image every time and disable cache
also this case is already handled in other image loaders. i suggest you to add this cache case too (when image file changes in server and url is the same image loader will know and reload the new image)

**Comment by luca992** [comment]
https://github.com/Kamel-Media/Kamel#memory-cache-size-number-of-entries-to-cache
https://github.com/Kamel-Media/Kamel#disk-cache-size-in-bytes
