### ISSUE TITLE
Make heavyweight dependencies optional

### ISSUE THREAD

**Issue by eskatos** [Kamel-Media/Kamel#89]
On the JVM platform, quite a lot of dependencies are brought in by default such as Batik.

It would be nice if these dependencies were optional and only supported if added by the developer.

For example, I don't need SVG support at all so I removed Batik with a Gradle exclude rule:

```kotlin
configurations {
    desktopMainImplementation {
        exclude(group = "org.apache.xmlgraphics")
    }
}
```

**Comment by luca992** [comment]
yeah, that's on the todo list #51

**Comment by eskatos** [comment]
I didn't realize this was the same issue. Sorry for the noise. Looking forward to it

**Comment by luca992** [comment]
@eskatos check out `implementation("media.kamel:kamel-image-default:1.0.0-beta.1")` You can choose pick and choose almost all parts now.

https://github.com/Kamel-Media/Kamel/pull/96
