### ISSUE TITLE
Support compose multiplatform for kotlin/JS [1.6.0]

### ISSUE THREAD

**Issue by Lukaszz112** [Kamel-Media/Kamel#98]
As in title, can we use kamel image for kotlin/js in compose 1.6.0, or when it will be possible?

**Comment by luca992** [comment]
Currently blocked by: https://github.com/JetBrains/compose-multiplatform/issues/4295

I can't build the `js` target 🙃

**Comment by luca992** [comment]
I worked around the issue by just commenting out resources in `kamel-core` and published `0.9.4` https://github.com/Kamel-Media/Kamel/releases/tag/v0.9.4
